name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main

    - name: Deploy to PSGallery
      env:
        PSGALLERY_TOKEN: ${{secrets.PSGALLERY_TOKEN}}
      shell: pwsh
      run: | 
        ./home/runner/work/PSScriptConfig/PSScriptConfig/main/.github/workflows/Deploy-PSScriptConfig.ps1