name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to PSGallery
    env:
      PSGALLERY_TOKEN: ${{secrets.PSGALLERY_TOKEN}}
    run: .github\workflows\Deploy-PSScriptConfig.ps1
    shell: pwsh